//signup
export const GET_SIGNUP = "GET_SIGNUP";
export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_FAILURE = "GET_SIGNUP_FAILURE";

//fieldInput
export const CHANGE_FIELD_INPUT = "CHANGE_FIELD_INPUT";

//login
export const GET_LOGIN = "GET_LOGIN";
export const GET_LOGIN_SUCCCESS = "GET_LOGIN_SUCCCESS";
export const GET_LOGIN_FAILURE = "GET_LOGIN_FAILURE";

//brands
export const GET_BRANDS ="GET_BRANDS";
export const GET_BRANDS_SUCCCESS = "GET_BRANDS_SUCCCESS";
export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE";

//chocolates
export const GET_CHOCOLATES = "GET_CHOCOLATES";
export const GET_CHOCOLATES_SUCCESS = "GET_CHOCOLATES_SUCCESS";
export const GET_CHOCOLATES_FAILURE = "GET_CHOCOLATES_FAILURE";


// //logout
// export const GET_LOGOUT = "GET_LOGOUT";
// export const GET_LOGOUT_SUCCESS = "GET_LOGOUT_SUCCESS";
// export const GET_LOGOUT_FAILURE = "GET_LOGOUT_FAILURE";

export const GET_DATA = "GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";